# Generated by Django 5.1.4 on 2025-01-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_technology_alter_task_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='technology',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
