# Generated by Django 5.1.4 on 2025-01-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_alter_task_technology_delete_technology'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
