# Generated by Django 5.1.4 on 2025-01-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_technology_alter_task_mail_id_alter_task_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='technology',
        ),
        migrations.AddField(
            model_name='task',
            name='technology',
            field=models.ManyToManyField(to='taskapp.technology'),
        ),
    ]
