# Generated by Django 5.1.4 on 2025-01-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_remove_task_technology_task_technology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
    ]
